name: Deploy MultiDocker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run tests
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

      - name: Build images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker